// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-IdM7j8UHZCm49dKuA10zVSCs9DUWZls',
    appId: '1:6146405680:web:41c7fca4e679cf77a6c4f5',
    messagingSenderId: '6146405680',
    projectId: 'anime-trade',
    authDomain: 'anime-trade.firebaseapp.com',
    storageBucket: 'anime-trade.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDipHgmFaEUgfxqC0G2XMdTYJjOUqzheIo',
    appId: '1:6146405680:android:c66bdab131e44bf7a6c4f5',
    messagingSenderId: '6146405680',
    projectId: 'anime-trade',
    storageBucket: 'anime-trade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKH0KyxU5pzP1xeEwjbW4CfGS2BLwaBS4',
    appId: '1:6146405680:ios:bdae986d0ffdac7da6c4f5',
    messagingSenderId: '6146405680',
    projectId: 'anime-trade',
    storageBucket: 'anime-trade.firebasestorage.app',
    iosBundleId: 'com.tiosam.animeTradeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKH0KyxU5pzP1xeEwjbW4CfGS2BLwaBS4',
    appId: '1:6146405680:ios:bdae986d0ffdac7da6c4f5',
    messagingSenderId: '6146405680',
    projectId: 'anime-trade',
    storageBucket: 'anime-trade.firebasestorage.app',
    iosBundleId: 'com.tiosam.animeTradeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-IdM7j8UHZCm49dKuA10zVSCs9DUWZls',
    appId: '1:6146405680:web:289105db51c76a07a6c4f5',
    messagingSenderId: '6146405680',
    projectId: 'anime-trade',
    authDomain: 'anime-trade.firebaseapp.com',
    storageBucket: 'anime-trade.firebasestorage.app',
  );
}
